baseURL             = "https://www.mariopardo.co/"
languageCode        = "en-us"
title               = "Mario Pardo"
theme               = "minimal"
googleAnalytics      = ""

[params]
latestpostcount     = 5
i18n_flags          = false
cachebuster         = false
author              = "Mario Pardo"
description         = "Personal blog"
githubUsername      = "darkadan"
accent              = "red"
showBorder          = true
backgroundColor     = "white"
font                = "Raleway" # should match the name on Google Fonts!
highlight           = true
highlightStyle      = "solarized-dark"
highlightLanguages  = ["go", "python", "kotlin", "javascript", "bash"]

[[menu.main]]
name                = "Home"
url                 = "/"
identifier          = "home"
weight              = 1

[[menu.main]]
name                = "Blog"
identifier          = "blog"
url                 = "/blog/"
weight              = 2

[[menu.main]]
name                = "Projects"
identifier          = "projects"
url                 = "/projects/"
weight              = 3

[[menu.main]]
name                = "Labs"
identifier          = "labs"
url                 = "/labs/"
weight              = 4

[[menu.main]]
name                = "About"
identifier          = "about"
url                 = "/about/"
weight              = 5

[[menu.main]]
name                = "Contact"
identifier          = "contact"
url                 = "/contact/"
weight              = 5

[permalinks]
blog = "blog/:year/:month/:day/:title/"

[[menu.icon]]
name                = "envelope-o"
url                 = "mailto:marioapardo@gmail.com"
weight              = 1

[[menu.icon]]
name                = "github"
url                 = "https://github.com/darkadan/"
weight              = 2

[[menu.icon]]
name                = "twitter"
url                 = "https://twitter.com/mariiopardo/"
weight              = 3

[[menu.icon]]
name                = "linkedin"
url                 = "https://www.linkedin.com/in/marioapardo/"
weight              = 4
