baseurl = "https://www.mariopardo.co/"
title = "Mario Pardo"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "es"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

defaultContentLanguageInSubdir = true

[params]
    title = "Mario Pardo"
    author = "Mario Pardo"
    avatarurl = "images/avatar.jpg"
    
    # dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[permalinks]
blog = "blog/:year/:month/:day/:title/"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/marioapardo/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/marioapardo/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/marioapardo0/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/marioapardo/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@marioapardo"


[languages]
    [languages.es]
        languagename = "Español"

        [languages.es.params]
            info = "CEO, DevOps y Consultor"
            description = "Sitio personal de Mario Pardo"
            keywords = "blog,desarrollador,personal"
            footercontent = "Hecho con <3 en Colombia"

        [languages.es.menu]

            [[languages.es.menu.main]]
            name = "Blog"
            weight = 1
            url = "/blog/"

            [[languages.es.menu.main]]
            name = "Proyectos"
            weight = 2
            url = "/projects/"

            [[languages.es.menu.main]]
            name = "Laboratorios"
            weight = 3
            url = "/labs/"

            [[languages.es.menu.main]]
            name = "Acerca de"
            weight = 4
            url = "/about/"

            [[languages.es.menu.main]]
            name = "Contacto"
            weight = 5
            url = "/contact/"

    [languages.en]
        languagename = "English"

        [languages.en.params]
            info = "CEO, DevOps and Consultant"
            description = "Mario Pardo's personal website"
            keywords = "blog,developer,personal"
            # footercontent = "Enter a text here."

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 1
        url = "/blog/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 2
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Labs"
        weight = 3
        url = "/labs/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 4
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"

    [languages.fr]
        languagename = "Francais"

        [languages.fr.params]
            info = "CEO, DevOps et consultant"
            description = "Site personnel de Mario Pardo"
            keywords = "blog, développeur, personnel"
            # footercontent = "Mettez du texte ici."

        [languages.fr.menu]

            [[languages.fr.menu.main]]
            name = "Blog"
            weight = 1
            url = "/blog/"

            [[languages.fr.menu.main]]
            name = "Projets"
            weight = 2
            url = "/projects/"

            [[languages.fr.menu.main]]
            name = "Laboratoires"
            weight = 3
            url = "/labs/"

            [[languages.fr.menu.main]]
            name = "À propos de"
            weight = 4
            url = "/about/"

            [[languages.fr.menu.main]]
            name = "Contact"
            weight = 5
            url = "/contact/"