baseURL = "https://www.mariopardo.co/"
languageCode = "en-us"
title = "Mario Pardo"
theme = "minimal"
# disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Personal blog"
    githubUsername = "darkadan"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "kotlin", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/lab/"
    name = "Labs"
    weight = 4

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:marioapardo@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/darkadan/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/mariiopardo/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/marioapardo/"
    name = "linkedin"
    weight = 4

# [[menu.icon]]
#     url = "https://stackoverflow.com/users/2438465/"
#     name = "stack-overflow"
#     weight = 5
